# Generated by Django 5.2.4 on 2025-07-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_alter_categoria_options_categoria_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas_imagenes/'),
        ),
    ]
