# Generated by Django 5.2.4 on 2025-07-29 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_receta_autor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='receta',
            name='usuario_baja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_dadas_de_baja', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Baja'),
        ),
    ]
