# Generated by Django 5.2.4 on 2025-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_receta_fecha_baja_receta_usuario_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
    ]
