# Generated by Django 5.2.4 on 2025-07-29 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0007_receta_fecha_modificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['fecha'], 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario_baja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_dados_de_baja', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Baja'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
