# Generated by Django 5.2.4 on 2025-07-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0008_alter_comentario_options_comentario_fecha_baja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.TextField(blank=True, help_text='Lista de ingredientes, separados por comas, puntos o en líneas diferentes.'),
        ),
    ]
